// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuK_FNmufnyM23Z19mQcNZXWdmE62wbOQ',
    appId: '1:846337587745:web:fdbb2af10dfc4fb3008160',
    messagingSenderId: '846337587745',
    projectId: 'mob-vendas-ddac5',
    authDomain: 'mob-vendas-ddac5.firebaseapp.com',
    storageBucket: 'mob-vendas-ddac5.appspot.com',
    measurementId: 'G-H2C90YEMFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEKSLE_qh_EOSDAlE9p7aepXJfb6ERmw0',
    appId: '1:846337587745:android:b518a6006a189723008160',
    messagingSenderId: '846337587745',
    projectId: 'mob-vendas-ddac5',
    storageBucket: 'mob-vendas-ddac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSmViGVJDTLDFltkAXWVs5Nf3aDq1joVQ',
    appId: '1:846337587745:ios:f830b12dd37fa5af008160',
    messagingSenderId: '846337587745',
    projectId: 'mob-vendas-ddac5',
    storageBucket: 'mob-vendas-ddac5.appspot.com',
    iosClientId: '846337587745-avp2gh34m4tpk241mlrmg8d5qg2ku4bd.apps.googleusercontent.com',
    iosBundleId: 'net.boginni.mobvendas.mobVendas',
  );
}
